### PR TITLE
Get the basics set up for sentry

### PR DESCRIPTION
**Pull request by justinvdm**
@smn depends on #221, otherwise ready for review.

### CODE REVIEW

**Comment by justinvdm** [comment]
Note for review: We still need to upload the bundle and sourcemaps for the bundle to sentry as release artefacts. This PR is just for the basics.

**Comment by smn** [comment]
I'm assuming this would mean we ship the apk with the sentry url baked in?

**Comment by smn** [comment]
:+1:

**Comment by justinvdm** [comment]
> I'm assuming this would mean we ship the apk with the sentry url baked in?

@smn yep, anything I'm missing that could make that a bad idea?

I guess it means a sentry url change would require users to download a new release. Is that case likely enough that we should avoid this approach?

**Comment by smn** [comment]
no I think that's fine

**Pull request merged**
