### PR TITLE
Indicate which outbound messages were sent automatically by the system

### PR DESCRIPTION
**Pull request by justinvdm**

### CODE REVIEW

**Comment by justinvdm** [comment]
@codiebeulaine ready for review

**Comment by justinvdm** [comment]
screen shot 2016-12-14 at 2 18 48 pm

**Comment by codiebeulaine** [comment]
@justinvdm :+1:

**Comment by justinvdm** [comment]
Removed negative margin for hint:
screen shot 2016-12-14 at 2 24 39 pm

**Comment by justinvdm** [comment]
@codiebeulaine Thanks for review :) made one minor change to bottom margin for hint, will land when travis is happy

**Comment by codiebeulaine** [comment]
@justinvdm :+1:

**Pull request merged**
