### PR TITLE
Loading screen action and view

### PR DESCRIPTION
**Pull request by justinvdm**
This is for adding an action creator for performing the initial load, and a corresponding loading view (uses the loading overlay component).

Was initially planning on adding the routing changes and hooking up of the `load()` action creator in this PR, but I think I need a better idea of how that should fit in with the current onboarding routes, and those changes seemed separate enough to leave for a separate PR.

### CODE REVIEW

**Comment by justinvdm** [comment]
@peterp ready for review

**Comment by peterp** [comment]
Very, very cool. 👍

**Comment by justinvdm** [comment]
@peterp made some changes (some of which we just discussed), ready for review.

**Comment by peterp** [comment]
👍

**Pull request merged**
