### PR TITLE
Match designs for call notes saved screen

### PR DESCRIPTION
**Pull request by justinvdm**
At the moment we don't match the designs, including the feature included in the designs for scheduling a call for the same time next week.

### CODE REVIEW

**Comment by justinvdm** [comment]
screen shot 2016-10-19 at 8 41 59 pm

**Comment by justinvdm** [comment]
screen shot 2016-10-19 at 8 41 59 pm
screen shot 2016-10-19 at 8 42 11 pm
screen shot 2016-10-19 at 8 56 02 pm

**Comment by justinvdm** [comment]
@smn @Mitso @projectmushroom ready for review

**Comment by smn** [comment]
:+1:

**Comment by Mitso** [comment]
💯

**Pull request merged**
