### PR TITLE
Button should accept `children` prop

### PR DESCRIPTION
**Pull request by peterp**
So that images can be Rendered.

### CODE REVIEW

**Comment by peterp** [comment]
@justinvdm ready for review

**Comment by peterp** [comment]
@justinvdm fixed merge conflict, ready for rereview.

**Comment by justinvdm** [comment]
:+1:

Considering we now need to uppercase explicitly for buttons, I'm wondering whether my suggestion to go this route was a good idea.

**Comment by peterp** [comment]
@justinvdm Perhaps I should check the type, and uppercase it if it's a string.

**Pull request merged**
