### PR TITLE
Feature/fix forgot password bugs

### PR DESCRIPTION
**Pull request by nathanbegbie**
TODO:
1) Update navigation so it's more intuitive 
2) Change text `Send password reminder`
3) Remove subtitle
4) Fix `Send Email` button not being pressable after 1 use

### CODE REVIEW

**Comment by nathanbegbie** [comment]
@justinvdm ready for review

**Comment by nathanbegbie** [comment]
screen shot 2017-05-24 at 3 18 56 pm
screen shot 2017-05-24 at 3 22 15 pm

**Comment by justinvdm** [comment]
Looks good :) :+1: once we are resetting status for unhandled api error responses.

**Comment by nathanbegbie** [comment]
@justinvdm ready for review again (stuff added post-review)

**Comment by justinvdm** [comment]
:+1:

**Pull request merged**
