### PR TITLE
Support both production and qa apks

### PR DESCRIPTION
**Pull request by justinvdm**
At the moment we only support production. Once we're live, we will need separate apks using separate configs.

### CODE REVIEW

**Comment by justinvdm** [comment]
@smn ready for review

**Comment by smn** [comment]
good idea but the travis build is failing

**Comment by justinvdm** [comment]
hrm, for some reason importing `react-native-config` makes tests timeout. I've changed the config stuff so it is only imported if we are in qa or prod, since we don't need it in tests and dev anyways. Actually running the app seems to work fine, so I'm guessing it has something to do with the fact that tests are run in a very different environment to the actual app.

**Comment by smn** [comment]
:+1: also it's late.

**Pull request merged**
