### PR TITLE
Respond to smaller screen sizes better for call note mood step

### PR DESCRIPTION
**Pull request by justinvdm**
@smn @Mitso @projectmushroom ready for review

### CODE REVIEW

**Comment by justinvdm** [comment]
screen shot 2016-10-27 at 9 56 31 pm
screen shot 2016-10-27 at 9 57 19 pm

**Comment by projectmushroom** [comment]
looking good, just a comment: the mood icons are not aligned

mood _big
mood _sml

**Comment by justinvdm** [comment]
@projectmushroom 🍰  for spotting :) will fix, thanks

**Comment by justinvdm** [comment]
@projectmushroom ready for re-review, thanks again for noticing the bad alignment
screen shot 2016-10-28 at 1 09 58 pm
screen shot 2016-10-28 at 1 10 54 pm

screen shot 2016-10-28 at 2 00 16 pm
screen shot 2016-10-28 at 2 00 22 pm

**Comment by projectmushroom** [comment]
Perfect! 👍

**Pull request merged**
