### PR TITLE
Fix chaining middleware to ignore actions dispatched from itself

### PR DESCRIPTION
**Pull request by justinvdm**

### CODE REVIEW

**Comment by justinvdm** [comment]
@peterp ready for review

**Comment by justinvdm** [comment]
Ok, now properly fixed and tested out in an emulator.

**Comment by peterp** [comment]
👍 , after travis is happy, are ypu fixing this for when we may need it again?

**Comment by justinvdm** [comment]
>  are ypu fixing this for when we may need it again?

@peterp I think we may still use this for api fetching.

**Pull request merged**
