### PR TITLE
Feature/gemmentor 446 update call notes summary screen

### PR DESCRIPTION
**Pull request by nathanbegbie**

### CODE REVIEW

**Comment by nathanbegbie** [comment]
@justinvdm ready for review. I'm not sure where more tests are needed if nec.

**Comment by justinvdm** [comment]
:+1: :cake:

@nathanbegbie looks good :) could you upload screenshots of the screen with and without the dismiss button (as a way of showing that we've visually verified the snapshot changes and additions)?

**Comment by nathanbegbie** [comment]
screen shot 2017-05-03 at 8 35 37 am
screen shot 2017-05-03 at 8 35 04 am

**Comment by justinvdm** [comment]
:+1:!

**Pull request merged**
