### PR TITLE
Add Blog detail view

### PR DESCRIPTION
**Pull request by justinvdm**

### CODE REVIEW

**Comment by justinvdm** [comment]
@codiebeualine @Mitso @nathanbegbie depends on #333 and #336, otherwise ready for review.

**Comment by justinvdm** [comment]
screen shot 2017-02-20 at 4 54 43 pm
screen shot 2017-02-20 at 4 54 48 pm
screen shot 2017-02-20 at 4 55 42 pm

**Comment by Mitso** [comment]
@justinvdm  :100: :cake: 

Is it possible to add a gif to get more context and the navigation flow maybe, but only if it doesn't take up a lot of your time :)

**Comment by justinvdm** [comment]
@Mitso thanks, and sure :) will add a gif to #337, since that is the PR where the navigation is wired up.

**Pull request merged**
