### PR TITLE
Tappable call completed event

### PR DESCRIPTION
**Pull request by justinvdm**
Tapping on a call completed event should allow the user to view call notes for the corresponding call.

### CODE REVIEW

**Comment by justinvdm** [comment]
screen shot 2016-10-25 at 5 43 33 pm

**Comment by justinvdm** [comment]
@smn @Mitso @projectmushroom ready for review

**Comment by justinvdm** [comment]
@smn @Mitso @projectmushroom reminder that this is ready for review :)

**Comment by projectmushroom** [comment]
@justinvdm sorry for not having any input for this project so far, I don't know React at all, but I am checking out your PRs as they come in

**Comment by smn** [comment]
sorry I missed this :+1:

**Comment by justinvdm** [comment]
> @justinvdm sorry for not having any input for this project so far, I don't know React at all, but I am checking out your PRs as they come in

@projectmushroom np, thanks :)

> sorry I missed this 👍

@smn np, thanks :)

**Pull request merged**
