### PR TITLE
Fixes and wiring up for blogs

### PR DESCRIPTION
**Pull request by justinvdm**

### CODE REVIEW

**Comment by justinvdm** [comment]
screen shot 2017-02-22 at 5 54 41 pm
screen shot 2017-02-22 at 5 54 50 pm

**Comment by justinvdm** [comment]
@codiebeulaine depends on #336, otherwise ready for review

**Comment by justinvdm** [comment]
@Mitso that gif you asked for, sorry for the delay.
blogs

**Comment by Mitso** [comment]
@justinvdm NP, 

Thanks, LGTM :+1:

**Pull request merged**
