### PR TITLE
Change Stepper to transition the same as the rest of the app

### PR DESCRIPTION
**Pull request by justinvdm**
@smn @Mitso @projectmushroom ready for review

### CODE REVIEW

**Comment by justinvdm** [comment]
This PR is mostly just boilerplate for switching to a different navigation setup that we get from react native.

**Comment by smn** [comment]
/me restarts the Travis build to see if it passes this time.

**Comment by smn** [comment]
:+1: when Travis

**Comment by justinvdm** [comment]
@smn thanks for review and restarting travis :)

**Pull request merged**
