### PR TITLE
Connecting Call view

### PR DESCRIPTION
**Pull request by justinvdm**

### CODE REVIEW

**Comment by justinvdm** [comment]
screen shot 2016-09-18 at 4 11 54 pm
screen shot 2016-09-18 at 4 35 15 pm
screen shot 2016-09-18 at 4 44 39 pm
screen shot 2016-09-18 at 4 45 56 pm

**Comment by justinvdm** [comment]
@peterp ready for review

**Comment by peterp** [comment]
Is that a Bloc Party reference?

**Comment by justinvdm** [comment]
> Is that a Bloc Party reference?

yep :)

**Pull request merged**
