### PR TITLE
RichText component styling for text

### PR DESCRIPTION
**Pull request by justinvdm**
@Mitso @nathanbegbie ready for review

### CODE REVIEW

**Comment by justinvdm** [comment]
(depends on #313, otherwise ready for review)

**Comment by justinvdm** [comment]
screen shot 2017-01-05 at 4 08 50 pm

**Comment by justinvdm** [comment]
screen shot 2017-01-05 at 5 00 28 pm

**Comment by Mitso** [comment]
@justinvdm +1
Strikeout text isn't strike-through

**Pull request merged**
